### ISSUE TITLE
[BUG] `env` 브랜치가 없음

### ISSUE THREAD

**Issue by ssaru** [HephaestusProject/pytorch_CNNSAClassification#1]
## 🐛 Bug

@Taekyoon 태균님, 레파지토리에 `env`브랜치가 없습니다.
Template 레포 사용하실 때, **Include all branches** 마크하셔서 생성 부탁드리겠습니다. 🙏

현 레포는 다시 만드시거나, 아니면 env 브랜치로 분기하셔서 Push하는 작업을 해야할 것 같습니다.

`env`레포는 추후, 쿠버네티스로 배포될 때, 사용할 릴리즈 브랜치 개념이라고 보시면 될 것 같습니다.

## To Reproduce

버그를 재현하기 위한 재현절차를 작성해주세요.

1. -
2. -
3. -

## Environment

실행한 환경을 확인하기 위해 `utils/collect_env.py`의 실행결과를 붙여넣어주세요. (`python3 utils/collect_env.py`)

```
실행결과 >>
Collecting environment information...
...

```

**Comment by Taekyoon** [comment]
@ssaru 동현님 깃헙에서 env 생성이 가능하여 먼저 브렌치를 따로 분기해 두었습니다.
혹시 master와 env 구성이 다른점이 있을까요?
Environment 실행 환경 확인은 추후에 진행하도록 하겠습니다.
